### ISSUE TITLE
DDS file written with mipmaps with `Dds::new_dxgi` is read as having no mipmaps.

### ISSUE THREAD

**Issue by ScanMountGoat** [SiegeEngine/ddsfile#9]
There's a check in the header read function that sets the mipmap count to `None` if the `MIPMAPCOUNT` flag is missing.
https://github.com/SiegeEngine/ddsfile/blob/1767a407e17f61124d9a1e8efd2e4a3e60e4014e/src/header.rs#L255-L259

The dxgi function never sets this flag, however. 
https://github.com/SiegeEngine/ddsfile/blob/1767a407e17f61124d9a1e8efd2e4a3e60e4014e/src/header.rs#L172

The mipmaps still show up in applications like RenderDoc and Photoshop CS6 when saving as dxgi. They just aren't recognized when calling `ddsfile::Dds::read`

I've attached an example created using `Dds::new_dxgi` with 7 mipmaps.
[example.zip](https://github.com/SiegeEngine/ddsfile/files/7878181/example.zip)

**Comment by mikedilger** [comment]
Looks like an oversight. I just pushed a fix (hopefully).

**Comment by ScanMountGoat** [comment]
It's working fine now on the latest commit. Thanks.
